const mockedData = [
    {
        name: 'RUN',
        data: [
            {
                mcid: 1,
                mc_sname: '122ISU00',
                startdate: '2021.03.29 08:00:00:000',
                enddate: '2021.03.29 10:00:00:000',
                rs_detail: 'Unknow',
                duration: '02h 00m 00s',
                tm_gg: '07h 31m 21s',
                tm_gf: '0s',
                tm_rr: '0s',
                tm_rf: '0s',
                tm_yy: '0s',
                tm_yf: '0s',
                tm_bb: '0s',
                tm_bf: '0s',
                tm_ww: '0s',
                tm_wf: '0s',
                tm_brk: '01h 40m 00s',
                tm_off: '0s',
            },
            {
                mcid: 1,
                mc_sname: '122IXU00',
                startdate: '2021.03.29 08:00:00:000',
                enddate: '2021.03.29 10:00:00:000',
                rs_detail: 'Unknow',
                duration: '02h 00m 00s',
                tm_gg: '07h 31m 21s',
                tm_gf: '0s',
                tm_rr: '0s',
                tm_rf: '0s',
                tm_yy: '0s',
                tm_yf: '0s',
                tm_bb: '0s',
                tm_bf: '0s',
                tm_ww: '0s',
                tm_wf: '0s',
                tm_brk: '01h 40m 00s',
                tm_off: '0s',
            },
            {
                mcid: 1,
                mc_sname: '122ISU00',
                startdate: '2021.03.29 10:10:00:000',
                enddate: '2021.03.29 12:10:00:000',
                rs_detail: 'Unknow',
                duration: '02h 00m 00s',
                tm_gg: '07h 31m 21s',
                tm_gf: '0s',
                tm_rr: '0s',
                tm_rf: '0s',
                tm_yy: '0s',
                tm_yf: '0s',
                tm_bb: '0s',
                tm_bf: '0s',
                tm_ww: '0s',
                tm_wf: '0s',
                tm_brk: '01h 40m 00s',
                tm_off: '0s',
            },
            {
                mcid: 1,
                mc_sname: '122ISU00',
                startdate: '2021.03.29 13:00:00:000',
                enddate: '2021.03.29 15:00:00:000',
                rs_detail: 'Unknow',
                duration: '02h 00m 00s',
                tm_gg: '07h 31m 21s',
                tm_gf: '0s',
                tm_rr: '0s',
                tm_rf: '0s',
                tm_yy: '0s',
                tm_yf: '0s',
                tm_bb: '0s',
                tm_bf: '0s',
                tm_ww: '0s',
                tm_wf: '0s',
                tm_brk: '01h 40m 00s',
                tm_off: '0s',
            },
            {
                mcid: 1,
                mc_sname: '122ISU00',
                startdate: '2021.03.29 15:10:00:000',
                enddate: '2021.03.29 16:00:00:000',
                rs_detail: 'Unknow',
                duration: '50m 00s',
                tm_gg: '07h 31m 21s',
                tm_gf: '0s',
                tm_rr: '0s',
                tm_rf: '0s',
                tm_yy: '0s',
                tm_yf: '0s',
                tm_bb: '0s',
                tm_bf: '0s',
                tm_ww: '0s',
                tm_wf: '0s',
                tm_brk: '01h 40m 00s',
                tm_off: '0s',
            },
            {
                mcid: 1,
                mc_sname: '122ISU00',
                startdate: '2021.03.29 16:30:00:000',
                enddate: '2021.03.29 17:11:21:500',
                rs_detail: 'Unknow',
                duration: '41m 21s',
                tm_gg: '07h 31m 21s',
                tm_gf: '0s',
                tm_rr: '0s',
                tm_rf: '0s',
                tm_yy: '0s',
                tm_yf: '0s',
                tm_bb: '0s',
                tm_bf: '0s',
                tm_ww: '0s',
                tm_wf: '0s',
                tm_brk: '01h 40m 00s',
                tm_off: '0s',
            },
        ],
    },
    { name: 'SETUP', data: [] },
    {
        name: 'STOP',
        data: [
            {
                mcid: 1,
                mc_sname: '122IXU00',
                startdate: '2021.03.29 10:10:00:000',
                enddate: '2021.03.29 11:10:00:000',
                rs_detail: 'Unknow',
                duration: '02h 00m 00s',
                tm_gg: '07h 31m 21s',
                tm_gf: '0s',
                tm_rr: '0s',
                tm_rf: '0s',
                tm_yy: '0s',
                tm_yf: '0s',
                tm_bb: '0s',
                tm_bf: '0s',
                tm_ww: '0s',
                tm_wf: '0s',
                tm_brk: '01h 40m 00s',
                tm_off: '0s',
            },
            {
                mcid: 2,
                mc_sname: '122ISU01',
                startdate: '2021.03.29 08:00:00:000',
                enddate: '2021.03.29 17:11:21:500',
                rs_detail: 'Unknow',
                duration: '09h 11m 21s',
                tm_gg: '0s',
                tm_gf: '0s',
                tm_rr: '09h 11m 21s',
                tm_rf: '0s',
                tm_yy: '0s',
                tm_yf: '0s',
                tm_bb: '0s',
                tm_bf: '0s',
                tm_ww: '0s',
                tm_wf: '0s',
                tm_brk: '0s',
                tm_off: '0s',
            },
        ],
    },
    { name: 'MAN', data: [] },
    { name: 'MATERIAL', data: [] },
    { name: 'PACKAGE', data: [] },
    { name: 'OTHER', data: [] },
    { name: 'OFF', data: [] },
    {
        name: 'BREAK',
        data: [
            {
                mcid: 1,
                mc_sname: '122ISU00',
                startdate: '2021.03.29 10:00:00:000',
                enddate: '2021.03.29 10:10:00:000',
                rs_detail: 'Break time',
                duration: '10m 00s',
                tm_gg: '07h 31m 21s',
                tm_gf: '0s',
                tm_rr: '0s',
                tm_rf: '0s',
                tm_yy: '0s',
                tm_yf: '0s',
                tm_bb: '0s',
                tm_bf: '0s',
                tm_ww: '0s',
                tm_wf: '0s',
                tm_brk: '01h 40m 00s',
                tm_off: '0s',
            },
            {
                mcid: 1,
                mc_sname: '122ISU00',
                startdate: '2021.03.29 12:10:00:000',
                enddate: '2021.03.29 13:00:00:000',
                rs_detail: 'Break time',
                duration: '50m 00s',
                tm_gg: '07h 31m 21s',
                tm_gf: '0s',
                tm_rr: '0s',
                tm_rf: '0s',
                tm_yy: '0s',
                tm_yf: '0s',
                tm_bb: '0s',
                tm_bf: '0s',
                tm_ww: '0s',
                tm_wf: '0s',
                tm_brk: '01h 40m 00s',
                tm_off: '0s',
            },
            {
                mcid: 1,
                mc_sname: '122ISU00',
                startdate: '2021.03.29 15:00:00:000',
                enddate: '2021.03.29 15:10:00:000',
                rs_detail: 'Break time',
                duration: '10m 00s',
                tm_gg: '07h 31m 21s',
                tm_gf: '0s',
                tm_rr: '0s',
                tm_rf: '0s',
                tm_yy: '0s',
                tm_yf: '0s',
                tm_bb: '0s',
                tm_bf: '0s',
                tm_ww: '0s',
                tm_wf: '0s',
                tm_brk: '01h 40m 00s',
                tm_off: '0s',
            },
            {
                mcid: 1,
                mc_sname: '122ISU00', //*
                startdate: '2021.03.29 16:00:00:000',  //*
                enddate: '2021.03.29 16:30:00:000', //*
                rs_detail: 'Break time',
                duration: '30m 00s',
                tm_gg: '07h 31m 21s',
                tm_gf: '0s',
                tm_rr: '0s',
                tm_rf: '0s',
                tm_yy: '0s',
                tm_yf: '0s',
                tm_bb: '0s',
                tm_bf: '0s',
                tm_ww: '0s',
                tm_wf: '0s',
                tm_brk: '01h 40m 00s',
                tm_off: '0s',
            },
        ],
    },
]

export  {mockedData}